name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.19.0] # Your project requires Node >= 18

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      # Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run ESLint check (code formatting + linting)
      - name: Lint check
        run: yarn lint

      # Run Jest tests
      - name: Run unit tests
        run: yarn test --coverage

      # Build React library
      - name: Build library
        run: yarn build

      # Build Storybook
      - name: Build Storybook
        run: yarn build-storybook
